# version: 2. 1
# jobs:
#   build:
#     docker:
#       - image: cimg/node:15.14.0
#
#     working_directory: ~/my-app
#
#     steps:
#       - checkout
#       - run: yarn install
#       - run: yarn test

version: '2.1'
orbs:
  node: circleci/node@4.1.0
jobs:
  install-node-example:
    docker:
      - image: circleci/node:stretch
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version
workflows:
  test_my_app:
    jobs:
      - install-node-example
